server: 
  port: 9001
spring: 
  application:  
    name: moocmall-mall #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/test?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
#自定义日志文件的输出位置
myLog:
  url: D:/result1.txt
